// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYO5mwBUtjq6QhXGzlqoSUoZgSj-ZsFBY',
    appId: '1:1069469230887:web:daf1c289f1243384f3ab02',
    messagingSenderId: '1069469230887',
    projectId: 'flutter-chat-app-ca003',
    authDomain: 'flutter-chat-app-ca003.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ca003.firebasestorage.app',
    measurementId: 'G-ZDV65V3EJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn2fpnbGd8phZXM8u1OF7DoLC6cCkDBGw',
    appId: '1:1069469230887:android:c10a03846460a7f9f3ab02',
    messagingSenderId: '1069469230887',
    projectId: 'flutter-chat-app-ca003',
    storageBucket: 'flutter-chat-app-ca003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFJPVcOMSru05udaVY_78C2dRtv-7XZY',
    appId: '1:1069469230887:ios:9123008824659ebcf3ab02',
    messagingSenderId: '1069469230887',
    projectId: 'flutter-chat-app-ca003',
    storageBucket: 'flutter-chat-app-ca003.firebasestorage.app',
    iosClientId: '1069469230887-b7b5kdtqgbq5r5chtkmp5f76rgj6fmf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYFJPVcOMSru05udaVY_78C2dRtv-7XZY',
    appId: '1:1069469230887:ios:9123008824659ebcf3ab02',
    messagingSenderId: '1069469230887',
    projectId: 'flutter-chat-app-ca003',
    storageBucket: 'flutter-chat-app-ca003.firebasestorage.app',
    iosClientId: '1069469230887-b7b5kdtqgbq5r5chtkmp5f76rgj6fmf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYO5mwBUtjq6QhXGzlqoSUoZgSj-ZsFBY',
    appId: '1:1069469230887:web:66eac6dab4a08994f3ab02',
    messagingSenderId: '1069469230887',
    projectId: 'flutter-chat-app-ca003',
    authDomain: 'flutter-chat-app-ca003.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ca003.firebasestorage.app',
    measurementId: 'G-LNB0WZ3MEZ',
  );
}
